/** Declaration file generated by dts-gen */

declare function queryparams(defaults: any): any;

declare namespace queryparams {
  function encode(options: any): any;
  function reconfigure(options: any): any;
  function schema(): any;
}

declare module "queryparams" {
  export = queryparams;
}
